name: Credly-Bot
permissions: {}

on:
  schedule:
    - cron: '20 8 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Download credly data
        uses: michaelcontento/credly-import-action@v1
        with:
          username: svarrogh1337
